In [ ]:
#Imported Data structures
#1 Numpy Arrary
#2 DataFrames
#3 Series


In [8]:
import numpy  as np
A = np.array([10,20,30,40,50])
print(A)

[10 20 30 40 50]


In [3]:
A[-1]

50

In [4]:
A[:3]

array([10, 20, 30])

In [5]:
A[0] = 60


In [9]:
for i in A: 
    print(i)

10
20
30
40
50


In [10]:
for i in range(5):
    print(A[i])

10
20
30
40
50


In [4]:
#image operations(NumPy)
import skimage.io as io
A = io.imread('Wallpaper.png', as_gray=True)
print(A.shape)


ModuleNotFoundError: No module named 'skimage'

In [8]:
import skimage.io as io

A = io.imread('Wallpaper.png', as_gray=True)
io.imshow(A)



ModuleNotFoundError: No module named 'skimage'

In [1]:
#HW Image operations(NumPy)
#TO increase the brightness of an image by 50%
import skimage.io as io     
A = io.imread('Wallpaper.png', as_gray=True)
A = A + 50
io.imsave('Wallpaper_Brightened.png', A)        


ModuleNotFoundError: No module named 'skimage'

In [4]:
#operators Numpy Array
import numpy as np
A = np.array([10,20,30,40,50])
B = np.array([1,2,3,4,5])
C = A + B
print(C)



[11 22 33 44 55]


In [5]:
import numpy as np
A = np.array([10,20,30,40,50])
B = np.array([10])
C = A + B
print(C)


[20 30 40 50 60]


In [6]:
A + 10

array([20, 30, 40, 50, 60])

In [ ]:
A<5 #Boolean Array

array([False, False, False, False, False])

In [8]:
A%2==0

array([ True,  True,  True,  True,  True])

In [9]:
G = np.array([33,55,56,98])
G%2==0

array([False, False,  True,  True])

In [10]:
55 + G

array([ 88, 110, 111, 153])

In [11]:
b1 = G <5
b2 = G % 2 == 0


In [ ]:
b1 & b2 # Bitwise AND operation 

array([False, False, False, False])

In [14]:
b1 | b2 # Bitwise OR operation

array([False, False,  True,  True])

In [15]:
G

array([33, 55, 56, 98])

In [16]:
G[b1 & b2] # Boolean Indexing
#Boolean Indexing



array([], dtype=int32)

In [ ]:
H = np.array [4,1,3,2, 8]

In [23]:
c1 = H<5
c2 = H % 2 == 0


TypeError: '<' not supported between instances of 'list' and 'int'

In [24]:
A


array([10, 20, 30, 40, 50])

In [25]:
A[b1 & b2] # Boolean Indexing

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 4

In [26]:
A[A>5]

array([10, 20, 30, 40, 50])

In [1]:
#np.where

In [3]:
G


NameError: name 'G' is not defined

In [4]:
A = np.array([10,20,30,40,50])

NameError: name 'np' is not defined

In [8]:
import numpy as np
A = np.array([40,80,30,20,10])

In [9]:
A

array([40, 80, 30, 20, 10])

In [ ]:
np.where(A<50, A+10,A+5) 

array([50, 85, 40, 30, 20])

In [11]:
np.where(A > 30, A, 0) # If A > 30 then A else 0

array([40, 80,  0,  0,  0])

In [17]:
np.where(A <= 100, A%10==5, A%10==0) # If A <= 100 then A%10==5 else A%10==0

array([False, False, False, False, False])

In [18]:
np.random.seed(50)
marks = np.random.randint(0, 100, 20)
marks

array([48, 96, 11, 33, 94,  4, 70, 70, 22,  5,  2, 95, 71, 68, 78, 35, 92,
       91, 26, 90])

In [20]:
# To give grace marks to students who scored less than 50
grace_marks = np.where(marks < 50, marks + 10, marks)    
print(grace_marks)

[58 96 21 43 94 14 70 70 32 15 12 95 71 68 78 45 92 91 36 90]


In [21]:
marks<50

array([ True, False,  True,  True, False,  True, False, False,  True,
        True,  True, False, False, False, False,  True, False, False,
        True, False])

In [22]:
grace_marks[marks < 50]

array([58, 21, 43, 14, 32, 15, 12, 45, 36])

In [3]:
import numpy as np
np.random.seed(1)
marks = np.random.randint(0, 100, (10,4))
print(marks)


[[37 12 72  9]
 [75  5 79 64]
 [16  1 76 71]
 [ 6 25 50 20]
 [18 84 11 28]
 [29 14 50 68]
 [87 87 94 96]
 [86 13  9  7]
 [63 61 22 57]
 [ 1  0 60 81]]


In [7]:
avg_marks = np.mean(marks, axis=1)
print(avg_marks)


[32.5  55.75 41.   25.25 35.25 40.25 91.   28.75 50.75 35.5 ]


In [8]:
#average marks of all students 
avg_marks = np.mean(marks, axis=0)
print(avg_marks)    

[41.8 30.2 52.3 50.1]


In [ ]:
#Panda (Data Analytics)
#1 DataFrame
#2 Series
